'use client'
import {useEffect,useState} from 'react'
import {nanoid} from 'nanoid'
import {DndContext,PointerSensor,closestCenter,useSensor,useSensors,type DragEndEvent} from '@dnd-kit/core'
import {SortableContext,verticalListSortingStrategy,useSortable,arrayMove} from '@dnd-kit/sortable'
import {CSS} from '@dnd-kit/utilities'
import {GripVertical,Plus,Copy,Trash2} from 'lucide-react'
import {EditorContent,useEditor} from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import Placeholder from '@tiptap/extension-placeholder'
import type {Page,Block} from '@/lib/storage'

function htmlFor(b:Block){if(b.type==='heading')return `<h${b.level||1}>${escapeHtml(b.text)}</h${b.level||1}>`;if(b.type==='bulletList')return `<ul><li>${escapeHtml(b.text)}</li></ul>`;if(b.type==='orderedList')return `<ol><li>${escapeHtml(b.text)}</li></ol>`;if(b.type==='blockquote')return `<blockquote>${escapeHtml(b.text)}</blockquote>`;if(b.type==='codeBlock')return `<pre><code>${escapeHtml(b.text)}</code></pre>`;return `<p>${escapeHtml(b.text)}</p>`}
function escapeHtml(s:string){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function Row({block,onUpdate,onDelete,onDuplicate,onAdd}:{block:Block;onUpdate:(v:Partial<Block>)=>void;onDelete:()=>void;onDuplicate:()=>void;onAdd:()=>void}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:block.id});const editor=useEditor({extensions:[StarterKit.configure({heading:{levels:[1,2,3]}}),Placeholder.configure({placeholder:'Napiš něco…'})],content:htmlFor(block),immediatelyRender:false,onUpdate:({editor:e})=>onUpdate({text:e.getText()})});useEffect(()=>{if(editor&&!editor.isFocused&&editor.getText()!==block.text)editor.commands.setContent(htmlFor(block),{emitUpdate:false})},[block.text,editor]);return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.5:1}} className="group relative flex items-start py-1"><div className="absolute -left-14 top-2 hidden items-center gap-1 md:flex opacity-0 group-hover:opacity-100"><button onClick={onAdd} className="rounded p-1 hover:bg-zinc-100 dark:hover:bg-zinc-900"><Plus size={15}/></button><button {...listeners} {...attributes} className="cursor-grab rounded p-1 hover:bg-zinc-100 dark:hover:bg-zinc-900"><GripVertical size={15}/></button></div><div className="min-w-0 flex-1">{editor&&<EditorContent editor={editor} className="tiptap"/>}</div><div className="ml-2 hidden items-center gap-1 group-hover:flex"><button onClick={onDuplicate} className="p-1"><Copy size={14}/></button><button onClick={onDelete} className="p-1 text-red-500"><Trash2 size={14}/></button></div></div>}

export default function Editor({page,onChange}:{page:Page;onChange:(p:Page)=>void}){const [blocks,setBlocks]=useState(page.blocks);const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}));useEffect(()=>setBlocks(page.blocks),[page.id]);const persist=(next:Block[])=>{setBlocks(next);onChange({...page,blocks:next,updatedAt:new Date().toISOString()})};const drag=(e:DragEndEvent)=>{if(!e.over||e.active.id===e.over.id)return;const a=blocks.findIndex(x=>x.id===e.active.id),b=blocks.findIndex(x=>x.id===e.over!.id);if(a>=0&&b>=0)persist(arrayMove(blocks,a,b))};const addAt=(i:number)=>persist([...blocks.slice(0,i+1),{id:nanoid(),type:'paragraph',text:''},...blocks.slice(i+1)]);return <article className="mx-auto max-w-3xl px-5 py-12 md:px-12 md:py-20"><div className="mb-6"><div className="mb-3 text-5xl">{page.icon||'📄'}</div><input value={page.title} onChange={e=>onChange({...page,title:e.target.value,updatedAt:new Date().toISOString()})} className="w-full bg-transparent text-4xl font-bold tracking-tight outline-none placeholder:text-zinc-300" placeholder="Bez názvu"/></div><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={drag}><SortableContext items={blocks.map(b=>b.id)} strategy={verticalListSortingStrategy}>{blocks.map((b,i)=><Row key={b.id} block={b} onAdd={()=>addAt(i)} onDelete={()=>persist(blocks.filter(x=>x.id!==b.id))} onDuplicate={()=>persist([...blocks.slice(0,i+1),{...b,id:nanoid()},...blocks.slice(i+1)])} onUpdate={u=>persist(blocks.map(x=>x.id===b.id?{...x,...u}:x))}/>)}</SortableContext></DndContext><button onClick={()=>addAt(blocks.length-1)} className="mt-4 flex items-center gap-2 text-sm text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200"><Plus size={15}/> Přidat blok</button></article>}
